@startuml

title __TEST's Class Diagram__\n

  namespace com.hx.grpc.test {
    class com.hx.grpc.test.StudentServiceGrpc {
        {static} + SERVICE_NAME : String
        {static} - METHODID_GET_REAL_NAME_BY_USERNAME : int
        {static} - getGetRealNameByUsernameMethod : MethodDescriptor<MyRequest, MyResponse>
        {static} - serviceDescriptor : ServiceDescriptor
        {static} + getGetRealNameByUsernameMethod()
        {static} + getServiceDescriptor()
        {static} + newBlockingStub()
        {static} + newFutureStub()
        {static} + newStub()
        - StudentServiceGrpc()
    }
  }
  

  namespace com.hx.grpc.test {
    class com.hx.grpc.test.StudentServiceGrpc.MethodHandlers {
        - methodId : int
        + invoke()
        + invoke()
        ~ MethodHandlers()
    }
  }
  

  namespace com.hx.grpc.test {
    abstract class com.hx.grpc.test.StudentServiceGrpc.StudentServiceBaseDescriptorSupplier {
        + getFileDescriptor()
        + getServiceDescriptor()
        ~ StudentServiceBaseDescriptorSupplier()
    }
  }
  

  namespace com.hx.grpc.test {
    class com.hx.grpc.test.StudentServiceGrpc.StudentServiceBlockingStub {
        + getRealNameByUsername()
        # build()
        - StudentServiceBlockingStub()
    }
  }
  

  namespace com.hx.grpc.test {
    class com.hx.grpc.test.StudentServiceGrpc.StudentServiceFileDescriptorSupplier {
        ~ StudentServiceFileDescriptorSupplier()
    }
  }
  

  namespace com.hx.grpc.test {
    class com.hx.grpc.test.StudentServiceGrpc.StudentServiceFutureStub {
        + getRealNameByUsername()
        # build()
        - StudentServiceFutureStub()
    }
  }
  

  namespace com.hx.grpc.test {
    abstract class com.hx.grpc.test.StudentServiceGrpc.StudentServiceImplBase {
        + bindService()
        + getRealNameByUsername()
    }
  }
  

  namespace com.hx.grpc.test {
    class com.hx.grpc.test.StudentServiceGrpc.StudentServiceMethodDescriptorSupplier {
        - methodName : String
        + getMethodDescriptor()
        ~ StudentServiceMethodDescriptorSupplier()
    }
  }
  

  namespace com.hx.grpc.test {
    class com.hx.grpc.test.StudentServiceGrpc.StudentServiceStub {
        + getRealNameByUsername()
        # build()
        - StudentServiceStub()
    }
  }
  

  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.MethodHandlers
  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.StudentServiceBaseDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.StudentServiceBlockingStub
  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.StudentServiceFileDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.StudentServiceFutureStub
  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.StudentServiceImplBase
  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.StudentServiceMethodDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc +-down- com.hx.grpc.test.StudentServiceGrpc.StudentServiceStub
  com.hx.grpc.test.StudentServiceGrpc.MethodHandlers .up.|> io.grpc.stub.ServerCalls.BidiStreamingMethod
  com.hx.grpc.test.StudentServiceGrpc.MethodHandlers .up.|> io.grpc.stub.ServerCalls.ClientStreamingMethod
  com.hx.grpc.test.StudentServiceGrpc.MethodHandlers .up.|> io.grpc.stub.ServerCalls.ServerStreamingMethod
  com.hx.grpc.test.StudentServiceGrpc.MethodHandlers .up.|> io.grpc.stub.ServerCalls.UnaryMethod
  com.hx.grpc.test.StudentServiceGrpc.MethodHandlers o-- com.hx.grpc.test.StudentServiceGrpc.StudentServiceImplBase : serviceImpl
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceBaseDescriptorSupplier .up.|> io.grpc.protobuf.ProtoFileDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceBaseDescriptorSupplier .up.|> io.grpc.protobuf.ProtoServiceDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceBlockingStub -up-|> io.grpc.stub.AbstractBlockingStub
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceFileDescriptorSupplier -up-|> com.hx.grpc.test.StudentServiceGrpc.StudentServiceBaseDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceFutureStub -up-|> io.grpc.stub.AbstractFutureStub
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceImplBase .up.|> io.grpc.BindableService
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceMethodDescriptorSupplier .up.|> io.grpc.protobuf.ProtoMethodDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceMethodDescriptorSupplier -up-|> com.hx.grpc.test.StudentServiceGrpc.StudentServiceBaseDescriptorSupplier
  com.hx.grpc.test.StudentServiceGrpc.StudentServiceStub -up-|> io.grpc.stub.AbstractAsyncStub


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
