@startuml

title __DISRUPTOR's Class Diagram__\n

  namespace com.hx.disruptor {
    class com.hx.disruptor.LongEvent {
        - value : long
        + setValue()
        + toString()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.LongEventFactory {
        + newInstance()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.LongEventHandler {
        {static} + counter : long
        + onEvent()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.LongEventOtherHandler {
        {static} + anotherCounter : long
        + onEvent()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.Main01 {
        {static} + main()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.Main02 {
        {static} + main()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.Main03_Lambda {
        {static} + main()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.Main04_ProducerSingleTest {
        {static} + main()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.Main_ExceptionHandler {
        {static} + main()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.Main_MutiConsumer {
        {static} + main()
    }
  }
  

  namespace com.hx.disruptor {
    class com.hx.disruptor.Main_WaitStrategy {
        {static} + main()
    }
  }
  

  com.hx.disruptor.LongEventFactory .up.|> com.lmax.disruptor.EventFactory
  com.hx.disruptor.LongEventHandler .up.|> com.lmax.disruptor.EventHandler
  com.hx.disruptor.LongEventOtherHandler .up.|> com.lmax.disruptor.EventHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
