@startuml

title __RECTORIMPL's Class Diagram__\n

  namespace com.serverimp {
    namespace rectorimpl {
      class com.serverimp.rectorimpl.ReactorServer {
          ~ MAXIN : int
          ~ MAXOUT : int
          ~ selector : Selector
          ~ serverSocket : ServerSocketChannel
          + run()
          ~ ReactorServer()
          ~ dispatch()
      }
    }
  }
  

  namespace com.serverimp {
    namespace rectorimpl {
      class com.serverimp.rectorimpl.ReactorServer.Acceptor {
          + run()
      }
    }
  }
  

  namespace com.serverimp {
    namespace rectorimpl {
      class com.serverimp.rectorimpl.ReactorServer.Handler {
          {static} ~ READING : int
          {static} ~ SENDING : int
          ~ input : ByteBuffer
          ~ output : ByteBuffer
          ~ sk : SelectionKey
          ~ socketChannel : SocketChannel
          ~ state : int
          + run()
          ~ Handler()
          ~ inputIsComplete()
          ~ outputIsComplete()
          ~ process()
          ~ read()
          ~ send()
      }
    }
  }
  

  namespace com.serverimp {
    namespace rectorimpl {
      class com.serverimp.rectorimpl.threadPoolHandler {
          {static} ~ PROCESSING : int
          {static} ~ pool : ExecutorService
          + run()
      }
    }
  }
  

  com.serverimp.rectorimpl.ReactorServer .up.|> java.lang.Runnable
  com.serverimp.rectorimpl.ReactorServer +-down- com.serverimp.rectorimpl.ReactorServer.Acceptor
  com.serverimp.rectorimpl.ReactorServer +-down- com.serverimp.rectorimpl.ReactorServer.Handler
  com.serverimp.rectorimpl.ReactorServer.Acceptor .up.|> java.lang.Runnable
  com.serverimp.rectorimpl.ReactorServer.Handler .up.|> java.lang.Runnable
  com.serverimp.rectorimpl.threadPoolHandler .up.|> java.lang.Runnable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
