// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OriginalDataCenter.proto

package com.kafka.packagedata.proto.devicestat;

/**
 * <pre>
 *{
 *“device_event_list”:[
 *{
 *“src_node”:”16131503” ,   //src_node中前四位车站编码为BCD，后四位为HEX
 *“event_time”:” 20200720120000” ,  //格式为“YYYYMMDDHH24mmss”
 *“state0”:”10”,     //HEX
 *“state1”:”11” ,     //HEX
 *“relate_node_id”:”00000000” ,   // relate_node_id中前四位车站编码为BCD，后四位为HEX
 *“action”:”00” ,     //HEX
 *“event_code”:”0A00” ,     //HEX
 *},
 *{}
 *]
 *}
 * </pre>
 *
 * Protobuf type {@code package.parse.hx.DeviceAfcEvent}
 */
public final class DeviceAfcEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:package.parse.hx.DeviceAfcEvent)
    DeviceAfcEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceAfcEvent.newBuilder() to construct.
  private DeviceAfcEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceAfcEvent() {
    srcNode_ = "";
    eventTime_ = "";
    state0_ = "";
    state1_ = "";
    relateNodeId_ = "";
    action_ = "";
    eventCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeviceAfcEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeviceAfcEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            srcNode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            eventTime_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            state0_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            state1_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            relateNodeId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            eventCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_DeviceAfcEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_DeviceAfcEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.class, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder.class);
  }

  public static final int SRC_NODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object srcNode_;
  /**
   * <code>string src_node = 1;</code>
   * @return The srcNode.
   */
  @java.lang.Override
  public java.lang.String getSrcNode() {
    java.lang.Object ref = srcNode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcNode_ = s;
      return s;
    }
  }
  /**
   * <code>string src_node = 1;</code>
   * @return The bytes for srcNode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSrcNodeBytes() {
    java.lang.Object ref = srcNode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcNode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TIME_FIELD_NUMBER = 2;
  private volatile java.lang.Object eventTime_;
  /**
   * <code>string event_time = 2;</code>
   * @return The eventTime.
   */
  @java.lang.Override
  public java.lang.String getEventTime() {
    java.lang.Object ref = eventTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventTime_ = s;
      return s;
    }
  }
  /**
   * <code>string event_time = 2;</code>
   * @return The bytes for eventTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTimeBytes() {
    java.lang.Object ref = eventTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE0_FIELD_NUMBER = 3;
  private volatile java.lang.Object state0_;
  /**
   * <code>string state0 = 3;</code>
   * @return The state0.
   */
  @java.lang.Override
  public java.lang.String getState0() {
    java.lang.Object ref = state0_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      state0_ = s;
      return s;
    }
  }
  /**
   * <code>string state0 = 3;</code>
   * @return The bytes for state0.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getState0Bytes() {
    java.lang.Object ref = state0_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      state0_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE1_FIELD_NUMBER = 4;
  private volatile java.lang.Object state1_;
  /**
   * <code>string state1 = 4;</code>
   * @return The state1.
   */
  @java.lang.Override
  public java.lang.String getState1() {
    java.lang.Object ref = state1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      state1_ = s;
      return s;
    }
  }
  /**
   * <code>string state1 = 4;</code>
   * @return The bytes for state1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getState1Bytes() {
    java.lang.Object ref = state1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      state1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RELATE_NODE_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object relateNodeId_;
  /**
   * <code>string relate_node_id = 5;</code>
   * @return The relateNodeId.
   */
  @java.lang.Override
  public java.lang.String getRelateNodeId() {
    java.lang.Object ref = relateNodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      relateNodeId_ = s;
      return s;
    }
  }
  /**
   * <code>string relate_node_id = 5;</code>
   * @return The bytes for relateNodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRelateNodeIdBytes() {
    java.lang.Object ref = relateNodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      relateNodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 6;
  private volatile java.lang.Object action_;
  /**
   * <code>string action = 6;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string action = 6;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_CODE_FIELD_NUMBER = 7;
  private volatile java.lang.Object eventCode_;
  /**
   * <code>string event_code = 7;</code>
   * @return The eventCode.
   */
  @java.lang.Override
  public java.lang.String getEventCode() {
    java.lang.Object ref = eventCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventCode_ = s;
      return s;
    }
  }
  /**
   * <code>string event_code = 7;</code>
   * @return The bytes for eventCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventCodeBytes() {
    java.lang.Object ref = eventCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSrcNodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srcNode_);
    }
    if (!getEventTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventTime_);
    }
    if (!getState0Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, state0_);
    }
    if (!getState1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, state1_);
    }
    if (!getRelateNodeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, relateNodeId_);
    }
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, action_);
    }
    if (!getEventCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, eventCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSrcNodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srcNode_);
    }
    if (!getEventTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventTime_);
    }
    if (!getState0Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, state0_);
    }
    if (!getState1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, state1_);
    }
    if (!getRelateNodeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, relateNodeId_);
    }
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, action_);
    }
    if (!getEventCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, eventCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kafka.packagedata.proto.devicestat.DeviceAfcEvent)) {
      return super.equals(obj);
    }
    com.kafka.packagedata.proto.devicestat.DeviceAfcEvent other = (com.kafka.packagedata.proto.devicestat.DeviceAfcEvent) obj;

    if (!getSrcNode()
        .equals(other.getSrcNode())) return false;
    if (!getEventTime()
        .equals(other.getEventTime())) return false;
    if (!getState0()
        .equals(other.getState0())) return false;
    if (!getState1()
        .equals(other.getState1())) return false;
    if (!getRelateNodeId()
        .equals(other.getRelateNodeId())) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (!getEventCode()
        .equals(other.getEventCode())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SRC_NODE_FIELD_NUMBER;
    hash = (53 * hash) + getSrcNode().hashCode();
    hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getEventTime().hashCode();
    hash = (37 * hash) + STATE0_FIELD_NUMBER;
    hash = (53 * hash) + getState0().hashCode();
    hash = (37 * hash) + STATE1_FIELD_NUMBER;
    hash = (53 * hash) + getState1().hashCode();
    hash = (37 * hash) + RELATE_NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRelateNodeId().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + EVENT_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getEventCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kafka.packagedata.proto.devicestat.DeviceAfcEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *{
   *“device_event_list”:[
   *{
   *“src_node”:”16131503” ,   //src_node中前四位车站编码为BCD，后四位为HEX
   *“event_time”:” 20200720120000” ,  //格式为“YYYYMMDDHH24mmss”
   *“state0”:”10”,     //HEX
   *“state1”:”11” ,     //HEX
   *“relate_node_id”:”00000000” ,   // relate_node_id中前四位车站编码为BCD，后四位为HEX
   *“action”:”00” ,     //HEX
   *“event_code”:”0A00” ,     //HEX
   *},
   *{}
   *]
   *}
   * </pre>
   *
   * Protobuf type {@code package.parse.hx.DeviceAfcEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:package.parse.hx.DeviceAfcEvent)
      com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_DeviceAfcEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_DeviceAfcEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.class, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder.class);
    }

    // Construct using com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      srcNode_ = "";

      eventTime_ = "";

      state0_ = "";

      state1_ = "";

      relateNodeId_ = "";

      action_ = "";

      eventCode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_DeviceAfcEvent_descriptor;
    }

    @java.lang.Override
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent getDefaultInstanceForType() {
      return com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent build() {
      com.kafka.packagedata.proto.devicestat.DeviceAfcEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent buildPartial() {
      com.kafka.packagedata.proto.devicestat.DeviceAfcEvent result = new com.kafka.packagedata.proto.devicestat.DeviceAfcEvent(this);
      result.srcNode_ = srcNode_;
      result.eventTime_ = eventTime_;
      result.state0_ = state0_;
      result.state1_ = state1_;
      result.relateNodeId_ = relateNodeId_;
      result.action_ = action_;
      result.eventCode_ = eventCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kafka.packagedata.proto.devicestat.DeviceAfcEvent) {
        return mergeFrom((com.kafka.packagedata.proto.devicestat.DeviceAfcEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kafka.packagedata.proto.devicestat.DeviceAfcEvent other) {
      if (other == com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.getDefaultInstance()) return this;
      if (!other.getSrcNode().isEmpty()) {
        srcNode_ = other.srcNode_;
        onChanged();
      }
      if (!other.getEventTime().isEmpty()) {
        eventTime_ = other.eventTime_;
        onChanged();
      }
      if (!other.getState0().isEmpty()) {
        state0_ = other.state0_;
        onChanged();
      }
      if (!other.getState1().isEmpty()) {
        state1_ = other.state1_;
        onChanged();
      }
      if (!other.getRelateNodeId().isEmpty()) {
        relateNodeId_ = other.relateNodeId_;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (!other.getEventCode().isEmpty()) {
        eventCode_ = other.eventCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kafka.packagedata.proto.devicestat.DeviceAfcEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kafka.packagedata.proto.devicestat.DeviceAfcEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object srcNode_ = "";
    /**
     * <code>string src_node = 1;</code>
     * @return The srcNode.
     */
    public java.lang.String getSrcNode() {
      java.lang.Object ref = srcNode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcNode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string src_node = 1;</code>
     * @return The bytes for srcNode.
     */
    public com.google.protobuf.ByteString
        getSrcNodeBytes() {
      java.lang.Object ref = srcNode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcNode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string src_node = 1;</code>
     * @param value The srcNode to set.
     * @return This builder for chaining.
     */
    public Builder setSrcNode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcNode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string src_node = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcNode() {
      
      srcNode_ = getDefaultInstance().getSrcNode();
      onChanged();
      return this;
    }
    /**
     * <code>string src_node = 1;</code>
     * @param value The bytes for srcNode to set.
     * @return This builder for chaining.
     */
    public Builder setSrcNodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcNode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventTime_ = "";
    /**
     * <code>string event_time = 2;</code>
     * @return The eventTime.
     */
    public java.lang.String getEventTime() {
      java.lang.Object ref = eventTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_time = 2;</code>
     * @return The bytes for eventTime.
     */
    public com.google.protobuf.ByteString
        getEventTimeBytes() {
      java.lang.Object ref = eventTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_time = 2;</code>
     * @param value The eventTime to set.
     * @return This builder for chaining.
     */
    public Builder setEventTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string event_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventTime() {
      
      eventTime_ = getDefaultInstance().getEventTime();
      onChanged();
      return this;
    }
    /**
     * <code>string event_time = 2;</code>
     * @param value The bytes for eventTime to set.
     * @return This builder for chaining.
     */
    public Builder setEventTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object state0_ = "";
    /**
     * <code>string state0 = 3;</code>
     * @return The state0.
     */
    public java.lang.String getState0() {
      java.lang.Object ref = state0_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state0_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state0 = 3;</code>
     * @return The bytes for state0.
     */
    public com.google.protobuf.ByteString
        getState0Bytes() {
      java.lang.Object ref = state0_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state0_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state0 = 3;</code>
     * @param value The state0 to set.
     * @return This builder for chaining.
     */
    public Builder setState0(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      state0_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string state0 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearState0() {
      
      state0_ = getDefaultInstance().getState0();
      onChanged();
      return this;
    }
    /**
     * <code>string state0 = 3;</code>
     * @param value The bytes for state0 to set.
     * @return This builder for chaining.
     */
    public Builder setState0Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      state0_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object state1_ = "";
    /**
     * <code>string state1 = 4;</code>
     * @return The state1.
     */
    public java.lang.String getState1() {
      java.lang.Object ref = state1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string state1 = 4;</code>
     * @return The bytes for state1.
     */
    public com.google.protobuf.ByteString
        getState1Bytes() {
      java.lang.Object ref = state1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string state1 = 4;</code>
     * @param value The state1 to set.
     * @return This builder for chaining.
     */
    public Builder setState1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      state1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string state1 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearState1() {
      
      state1_ = getDefaultInstance().getState1();
      onChanged();
      return this;
    }
    /**
     * <code>string state1 = 4;</code>
     * @param value The bytes for state1 to set.
     * @return This builder for chaining.
     */
    public Builder setState1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      state1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object relateNodeId_ = "";
    /**
     * <code>string relate_node_id = 5;</code>
     * @return The relateNodeId.
     */
    public java.lang.String getRelateNodeId() {
      java.lang.Object ref = relateNodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        relateNodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string relate_node_id = 5;</code>
     * @return The bytes for relateNodeId.
     */
    public com.google.protobuf.ByteString
        getRelateNodeIdBytes() {
      java.lang.Object ref = relateNodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        relateNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string relate_node_id = 5;</code>
     * @param value The relateNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setRelateNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      relateNodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string relate_node_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRelateNodeId() {
      
      relateNodeId_ = getDefaultInstance().getRelateNodeId();
      onChanged();
      return this;
    }
    /**
     * <code>string relate_node_id = 5;</code>
     * @param value The bytes for relateNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setRelateNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      relateNodeId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>string action = 6;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action = 6;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action = 6;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string action = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>string action = 6;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object eventCode_ = "";
    /**
     * <code>string event_code = 7;</code>
     * @return The eventCode.
     */
    public java.lang.String getEventCode() {
      java.lang.Object ref = eventCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_code = 7;</code>
     * @return The bytes for eventCode.
     */
    public com.google.protobuf.ByteString
        getEventCodeBytes() {
      java.lang.Object ref = eventCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_code = 7;</code>
     * @param value The eventCode to set.
     * @return This builder for chaining.
     */
    public Builder setEventCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string event_code = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventCode() {
      
      eventCode_ = getDefaultInstance().getEventCode();
      onChanged();
      return this;
    }
    /**
     * <code>string event_code = 7;</code>
     * @param value The bytes for eventCode to set.
     * @return This builder for chaining.
     */
    public Builder setEventCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      eventCode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:package.parse.hx.DeviceAfcEvent)
  }

  // @@protoc_insertion_point(class_scope:package.parse.hx.DeviceAfcEvent)
  private static final com.kafka.packagedata.proto.devicestat.DeviceAfcEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kafka.packagedata.proto.devicestat.DeviceAfcEvent();
  }

  public static com.kafka.packagedata.proto.devicestat.DeviceAfcEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceAfcEvent>
      PARSER = new com.google.protobuf.AbstractParser<DeviceAfcEvent>() {
    @java.lang.Override
    public DeviceAfcEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeviceAfcEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceAfcEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceAfcEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

