// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OriginalDataCenter.proto

package com.kafka.packagedata.proto.devicestat;

/**
 * Protobuf type {@code package.parse.hx.OriginalAfcDeviceState}
 */
public final class OriginalAfcDeviceState extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:package.parse.hx.OriginalAfcDeviceState)
    OriginalAfcDeviceStateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OriginalAfcDeviceState.newBuilder() to construct.
  private OriginalAfcDeviceState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OriginalAfcDeviceState() {
    deviceEventList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OriginalAfcDeviceState();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OriginalAfcDeviceState(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              deviceEventList_ = new java.util.ArrayList<com.kafka.packagedata.proto.devicestat.DeviceAfcEvent>();
              mutable_bitField0_ |= 0x00000001;
            }
            deviceEventList_.add(
                input.readMessage(com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        deviceEventList_ = java.util.Collections.unmodifiableList(deviceEventList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_OriginalAfcDeviceState_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_OriginalAfcDeviceState_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState.class, com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState.Builder.class);
  }

  public static final int DEVICE_EVENT_LIST_FIELD_NUMBER = 1;
  private java.util.List<com.kafka.packagedata.proto.devicestat.DeviceAfcEvent> deviceEventList_;
  /**
   * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.kafka.packagedata.proto.devicestat.DeviceAfcEvent> getDeviceEventListList() {
    return deviceEventList_;
  }
  /**
   * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder> 
      getDeviceEventListOrBuilderList() {
    return deviceEventList_;
  }
  /**
   * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
   */
  @java.lang.Override
  public int getDeviceEventListCount() {
    return deviceEventList_.size();
  }
  /**
   * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
   */
  @java.lang.Override
  public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent getDeviceEventList(int index) {
    return deviceEventList_.get(index);
  }
  /**
   * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
   */
  @java.lang.Override
  public com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder getDeviceEventListOrBuilder(
      int index) {
    return deviceEventList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < deviceEventList_.size(); i++) {
      output.writeMessage(1, deviceEventList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < deviceEventList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, deviceEventList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState)) {
      return super.equals(obj);
    }
    com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState other = (com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState) obj;

    if (!getDeviceEventListList()
        .equals(other.getDeviceEventListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDeviceEventListCount() > 0) {
      hash = (37 * hash) + DEVICE_EVENT_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceEventListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code package.parse.hx.OriginalAfcDeviceState}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:package.parse.hx.OriginalAfcDeviceState)
      com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceStateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_OriginalAfcDeviceState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_OriginalAfcDeviceState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState.class, com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState.Builder.class);
    }

    // Construct using com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDeviceEventListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (deviceEventListBuilder_ == null) {
        deviceEventList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        deviceEventListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.kafka.packagedata.proto.devicestat.devicestat.internal_static_package_parse_hx_OriginalAfcDeviceState_descriptor;
    }

    @java.lang.Override
    public com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState getDefaultInstanceForType() {
      return com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState.getDefaultInstance();
    }

    @java.lang.Override
    public com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState build() {
      com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState buildPartial() {
      com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState result = new com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState(this);
      int from_bitField0_ = bitField0_;
      if (deviceEventListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          deviceEventList_ = java.util.Collections.unmodifiableList(deviceEventList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.deviceEventList_ = deviceEventList_;
      } else {
        result.deviceEventList_ = deviceEventListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState) {
        return mergeFrom((com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState other) {
      if (other == com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState.getDefaultInstance()) return this;
      if (deviceEventListBuilder_ == null) {
        if (!other.deviceEventList_.isEmpty()) {
          if (deviceEventList_.isEmpty()) {
            deviceEventList_ = other.deviceEventList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDeviceEventListIsMutable();
            deviceEventList_.addAll(other.deviceEventList_);
          }
          onChanged();
        }
      } else {
        if (!other.deviceEventList_.isEmpty()) {
          if (deviceEventListBuilder_.isEmpty()) {
            deviceEventListBuilder_.dispose();
            deviceEventListBuilder_ = null;
            deviceEventList_ = other.deviceEventList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            deviceEventListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDeviceEventListFieldBuilder() : null;
          } else {
            deviceEventListBuilder_.addAllMessages(other.deviceEventList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.kafka.packagedata.proto.devicestat.DeviceAfcEvent> deviceEventList_ =
      java.util.Collections.emptyList();
    private void ensureDeviceEventListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        deviceEventList_ = new java.util.ArrayList<com.kafka.packagedata.proto.devicestat.DeviceAfcEvent>(deviceEventList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.kafka.packagedata.proto.devicestat.DeviceAfcEvent, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder, com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder> deviceEventListBuilder_;

    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public java.util.List<com.kafka.packagedata.proto.devicestat.DeviceAfcEvent> getDeviceEventListList() {
      if (deviceEventListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deviceEventList_);
      } else {
        return deviceEventListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public int getDeviceEventListCount() {
      if (deviceEventListBuilder_ == null) {
        return deviceEventList_.size();
      } else {
        return deviceEventListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent getDeviceEventList(int index) {
      if (deviceEventListBuilder_ == null) {
        return deviceEventList_.get(index);
      } else {
        return deviceEventListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder setDeviceEventList(
        int index, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent value) {
      if (deviceEventListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceEventListIsMutable();
        deviceEventList_.set(index, value);
        onChanged();
      } else {
        deviceEventListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder setDeviceEventList(
        int index, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder builderForValue) {
      if (deviceEventListBuilder_ == null) {
        ensureDeviceEventListIsMutable();
        deviceEventList_.set(index, builderForValue.build());
        onChanged();
      } else {
        deviceEventListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder addDeviceEventList(com.kafka.packagedata.proto.devicestat.DeviceAfcEvent value) {
      if (deviceEventListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceEventListIsMutable();
        deviceEventList_.add(value);
        onChanged();
      } else {
        deviceEventListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder addDeviceEventList(
        int index, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent value) {
      if (deviceEventListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeviceEventListIsMutable();
        deviceEventList_.add(index, value);
        onChanged();
      } else {
        deviceEventListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder addDeviceEventList(
        com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder builderForValue) {
      if (deviceEventListBuilder_ == null) {
        ensureDeviceEventListIsMutable();
        deviceEventList_.add(builderForValue.build());
        onChanged();
      } else {
        deviceEventListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder addDeviceEventList(
        int index, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder builderForValue) {
      if (deviceEventListBuilder_ == null) {
        ensureDeviceEventListIsMutable();
        deviceEventList_.add(index, builderForValue.build());
        onChanged();
      } else {
        deviceEventListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder addAllDeviceEventList(
        java.lang.Iterable<? extends com.kafka.packagedata.proto.devicestat.DeviceAfcEvent> values) {
      if (deviceEventListBuilder_ == null) {
        ensureDeviceEventListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deviceEventList_);
        onChanged();
      } else {
        deviceEventListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder clearDeviceEventList() {
      if (deviceEventListBuilder_ == null) {
        deviceEventList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        deviceEventListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public Builder removeDeviceEventList(int index) {
      if (deviceEventListBuilder_ == null) {
        ensureDeviceEventListIsMutable();
        deviceEventList_.remove(index);
        onChanged();
      } else {
        deviceEventListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder getDeviceEventListBuilder(
        int index) {
      return getDeviceEventListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder getDeviceEventListOrBuilder(
        int index) {
      if (deviceEventListBuilder_ == null) {
        return deviceEventList_.get(index);  } else {
        return deviceEventListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public java.util.List<? extends com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder> 
         getDeviceEventListOrBuilderList() {
      if (deviceEventListBuilder_ != null) {
        return deviceEventListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deviceEventList_);
      }
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder addDeviceEventListBuilder() {
      return getDeviceEventListFieldBuilder().addBuilder(
          com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder addDeviceEventListBuilder(
        int index) {
      return getDeviceEventListFieldBuilder().addBuilder(
          index, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .package.parse.hx.DeviceAfcEvent device_event_list = 1;</code>
     */
    public java.util.List<com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder> 
         getDeviceEventListBuilderList() {
      return getDeviceEventListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.kafka.packagedata.proto.devicestat.DeviceAfcEvent, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder, com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder> 
        getDeviceEventListFieldBuilder() {
      if (deviceEventListBuilder_ == null) {
        deviceEventListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.kafka.packagedata.proto.devicestat.DeviceAfcEvent, com.kafka.packagedata.proto.devicestat.DeviceAfcEvent.Builder, com.kafka.packagedata.proto.devicestat.DeviceAfcEventOrBuilder>(
                deviceEventList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        deviceEventList_ = null;
      }
      return deviceEventListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:package.parse.hx.OriginalAfcDeviceState)
  }

  // @@protoc_insertion_point(class_scope:package.parse.hx.OriginalAfcDeviceState)
  private static final com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState();
  }

  public static com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OriginalAfcDeviceState>
      PARSER = new com.google.protobuf.AbstractParser<OriginalAfcDeviceState>() {
    @java.lang.Override
    public OriginalAfcDeviceState parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OriginalAfcDeviceState(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OriginalAfcDeviceState> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OriginalAfcDeviceState> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.kafka.packagedata.proto.devicestat.OriginalAfcDeviceState getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

