@startuml

title __CONTAINERTEST's Class Diagram__\n

  namespace com.juc.sync {
    namespace containerTest {
      class com.juc.sync.containerTest.TestWithCountDownLatch {
          ~ lists : List
          + addElement()
          + listSize()
          {static} + main()
      }
    }
  }
  

  namespace com.juc.sync {
    namespace containerTest {
      class com.juc.sync.containerTest.TestWithLockSupport {
          ~ lists : List
          + addElement()
          + listSize()
          {static} + main()
      }
    }
  }
  

  namespace com.juc.sync {
    namespace containerTest {
      class com.juc.sync.containerTest.TestWithSemaphore {
          ~ lists : List
          {static} ~ t1 : Thread
          {static} ~ t2 : Thread
          + addElement()
          + listSize()
          {static} + main()
      }
    }
  }
  

  namespace com.juc.sync {
    namespace containerTest {
      class com.juc.sync.containerTest.TestWithVolatile {
          ~ lists : List
          + addElement()
          + listSize()
          {static} + main()
      }
    }
  }
  

  namespace com.juc.sync {
    namespace containerTest {
      class com.juc.sync.containerTest.TestWithWaitNotify {
          ~ lists : List
          + addElement()
          + listSize()
          {static} + main()
      }
    }
  }
  

  namespace com.juc.sync {
    namespace containerTest {
      class com.juc.sync.containerTest.TestWithWaitNotify_01 {
          ~ lists : List
          + addElement()
          + listSize()
          {static} + main()
      }
    }
  }
  

  namespace com.juc.sync {
    namespace containerTest {
      class com.juc.sync.containerTest.TestWithoutVolatile {
          ~ lists : List
          + addElement()
          + listSize()
          {static} + main()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
