@startuml

title __ABSTRATORY's Class Diagram__\n

  namespace com.sinohx.design.abstratory {
    class com.sinohx.design.abstratory.AppTest {
        + AppTest()
        + intTest()
    }
  }
  

  namespace com.sinohx.design.abstratory {
    class com.sinohx.design.abstratory.Concrete1Impl {
        ~ name : String
        + Encoder()
        + getName()
        + setName()
    }
  }
  

  namespace com.sinohx.design.abstratory {
    class com.sinohx.design.abstratory.Concrete2Impl {
        ~ name : String
        + Encoder()
        + getName()
        + setName()
    }
  }
  

  namespace com.sinohx.design.abstratory {
    interface com.sinohx.design.abstratory.IEncodeDecode {
        {abstract} + Encoder()
    }
  }
  

  namespace com.sinohx.design.abstratory {
    class com.sinohx.design.abstratory.abstractoryTest {
        {static} + main()
    }
  }
  

  namespace com.sinohx.design.abstratory {
    interface com.sinohx.design.abstratory.encodeDecodeFactory {
        {abstract} + GetEncoderDecoder()
    }
  }
  

  namespace com.sinohx.design.abstratory {
    class com.sinohx.design.abstratory.encodeDecodeFactoryImpl {
        + GetEncoderDecoder()
    }
  }
  

  com.sinohx.design.abstratory.AppTest o-- com.sinohx.design.abstratory.IEncodeDecode : iEncodeDecode
  com.sinohx.design.abstratory.Concrete1Impl .up.|> com.sinohx.design.abstratory.IEncodeDecode
  com.sinohx.design.abstratory.Concrete2Impl .up.|> com.sinohx.design.abstratory.IEncodeDecode
  com.sinohx.design.abstratory.encodeDecodeFactoryImpl .up.|> com.sinohx.design.abstratory.encodeDecodeFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
